export const defaultPlanId = "free"

export const pricingPlans = [
  {
    id: "free",
    name: "Free",
    description: "Découvrez VocalAI gratuitement",
    price: "0€",
    priceIntervalName: "par mois",
    stripe_price_id: null,
    features: [
      "10 minutes d'appels gratuits",
      "1 agent IA",
      "Support communautaire",
      "Dashboard basique",
    ],
  },
  {
    id: "starter",
    name: "Starter",
    description: "Parfait pour démarrer avec l'IA vocale",
    price: "69€",
    priceIntervalName: "par mois",
    stripe_price_id: "price_1Rr1ZpQWT4vGRsrSscDRNbxk",
    stripe_product_id: "prod_ShZEET8aD1OCgK",
    features: [
      "180 minutes d'appels par mois",
      "3 agents IA personnalisés",
      "Support par email",
      "Analytics de base",
      "Intégration CRM",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    description: "Pour les professionnels exigeants",
    price: "189€",
    priceIntervalName: "par mois",
    stripe_price_id: "price_1Rr1ZqQWT4vGRsrShErINWcb",
    stripe_product_id: "prod_ShZFMx5KeXykZX",
    features: [
      "540 minutes d'appels par mois",
      "10 agents IA personnalisés",
      "Support prioritaire",
      "Analytics avancés",
      "API complète",
      "Formation personnalisée",
    ],
  },
  {
    id: "business",
    name: "Business",
    description: "Solution complète pour les entreprises",
    price: "329€",
    priceIntervalName: "par mois",
    stripe_price_id: "price_1Rr1ZqQWT4vGRsrS4xSfJnUw",
    stripe_product_id: "prod_ShZFfyABEFRiY1",
    features: [
      "1080 minutes d'appels par mois",
      "Agents IA illimités",
      "Support dédié 24/7",
      "Analytics temps réel",
      "API entreprise",
      "Manager de compte dédié",
      "SLA garanti",
    ],
  },
]
